import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // CSES Solutions sidebar
  csesSidebar: [
    'cses/intro',
    {
      type: 'category',
      label: 'Dynamic Programming',
      items: [
        'cses/dynamic-programming/intro',
        'cses/dynamic-programming/coin-combinations-i',
        'cses/dynamic-programming/coin-combinations-ii',
      ],
    },
    {
      type: 'category',
      label: 'Graph Algorithms',
      items: [
        'cses/graph-algorithms/intro',
        'cses/graph-algorithms/counting-rooms',
      ],
    },
  ],

  // Keep existing tutorial sidebar
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
